default: &default
  twitter_key: <%= ENV["TWITTER_KEY"] %>
  twitter_secret: <%= ENV["TWITTER_SECRET"] %>
  facebook_key: <%= ENV["FACEBOOK_KEY"] %>
  facebook_secret: <%= ENV["FACEBOOK_SECRET"] %>
  google_oauth2_key: <%= ENV["GOOGLE_KEY"] %>
  google_oauth2_secret: <%= ENV["GOOGLE_SECRET"] %>
  openam_username: <%= ENV["OPENAM_USERNAME"] %>
  openam_password: <%= ENV["OPENAM_PASSWORD"] %>
  saml_issuer: <%= ENV["SAML_ISSUER"] || "consul" %>
  saml_idp_cert: <%= ENV["SAML_IDP_CERT"] %>
  saml_idp_sso_target_url: <%= ENV["SAML_IDP_URL"] || "http://localhost:8081/openam/idpssoinit?metaAlias=/idp&spEntityID=consul&binding=HTTP-POST" %>
  saml_name_identifier_format: <%= ENV["SAML_NAME_IDENTIFIER_FORMAT"] || "urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress" %>
  soap_url_svd: <%= ENV["SOAP_URL_SVD"] %>
  soap_url_pet: <%= ENV["SOAP_URL_PET"] %>
  soap_url_ver: <%= ENV["SOAP_URL_VER"] %>
  soap_url_ver1: <%= ENV["SOAP_URL_VER1"] %>
  soap_url_amb: <%= ENV["SOAP_URL_AMB"] %>
  soap_url_ns8: <%= ENV["SOAP_URL_NS8"] %>
  recaptcha_site_key: <%= ENV["RECAPTCHA_SITE_KEY"] %>
  recaptcha_secret_key: <%= ENV["RECAPTCHA_SECRET_KEY"] %>

maps: &maps
  map_tiles_provider: "//{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
  map_tiles_provider_attribution: "&copy; <a href=\"http://osm.org/copyright\">OpenStreetMap</a> contributors"

apis: &apis
  census_api_end_point: ""
  census_api_institution_code: ""
  census_api_portal_name: ""
  census_api_user_code: ""
  sms_end_point:  ""
  sms_username: ""
  sms_password: ""

http_basic_auth: &http_basic_auth
  http_basic_auth: true

development:
  <<: *default
  secret_key_base: <%= ENV["SECRET_TOKEN"] || "577c1fa795d63ea6b52c79303ead1e855902044f303ca5052a8b6b16a1f7a99e069c91bb0e646ac1fd69ed63c944e7954e54d0448fd88436f232822cb50c1be1" %>
  http_basic_username: "dev"
  http_basic_password: "pass"
  openam_username: <%= ENV["OPENAM_USERNAME"] || "amAdmin" %>
  openam_password: <%= ENV["OPENAM_PASSWORD"] || "123456789" %>
  <<: *maps

test:
  <<: *default
  secret_key_base: "577c1fa795d63ea6b52c79303ead1e855902044f303ca5052a8b6b16a1f7a99e069c91bb0e646ac1fd69ed63c944e7954e54d0448fd88436f232822cb50c1be1"
  openam_username: <%= ENV["OPENAM_USERNAME"] || "amAdmin" %>
  openam_password: <%= ENV["OPENAM_PASSWORD"] || "123456789" %>
  <<: *maps

staging:
  <<: *default
  <<: *maps
  <<: *apis
  secret_key_base: <%= ENV["SECRET_TOKEN"] %>
  server_name: ""
  rollbar_server_token: ""
  http_basic_username: ""
  http_basic_password: ""
  managers_url: ""
  managers_application_key: ""

preproduction:
  secret_key_base: <%= ENV["SECRET_TOKEN"] %>
  server_name: ""
  rollbar_server_token: ""
  http_basic_username: ""
  http_basic_password: ""
  managers_url: ""
  managers_application_key: ""
  twitter_key: ""
  twitter_secret: ""
  facebook_key: ""
  facebook_secret: ""
  google_oauth2_key: ""
  google_oauth2_secret: ""
  saml_issuer: ""
  saml_idp_cert: ""
  saml_idp_sso_target_url: ""
  saml_name_identifier_format: ""
  recaptcha_site_key: <%= ENV["RECAPTCHA_SITE_KEY"] %>
  recaptcha_secret_key: <%= ENV["RECAPTCHA_SECRET_KEY"] %>
  <<: *maps
  <<: *apis

production:
  secret_key_base: <%= ENV["SECRET_TOKEN"] %>
  server_name: "<%= ENV["SERVER_NAME"] %>"
  rollbar_server_token: ""
  http_basic_username: ""
  http_basic_password: ""
  managers_url: ""
  managers_application_key: ""
  twitter_key: <%= ENV["TWITTER_KEY"] %>
  twitter_secret: <%= ENV["TWITTER_SECRET"] %>
  facebook_key: <%= ENV["FACEBOOK_KEY"] %>
  facebook_secret: <%= ENV["FACEBOOK_SECRET"] %>
  google_oauth2_key: <%= ENV["GOOGLE_KEY"] %>
  google_oauth2_secret: <%= ENV["GOOGLE_SECRET"] %>
  saml_issuer: <%= ENV["SAML_ISSUER"] %>
  saml_idp_cert: <%= ENV["SAML_IDP_CERT"] %>
  saml_idp_sso_target_url: <%= ENV["SAML_IDP_URL"] %>
  saml_name_identifier_format: <%= ENV["SAML_NAME_IDENTIFIER_FORMAT"] %>
  recaptcha_site_key: <%= ENV["RECAPTCHA_SITE_KEY"] %>
  recaptcha_secret_key: <%= ENV["RECAPTCHA_SECRET_KEY"] %>
  <<: *maps
  <<: *apis
